# Generated by Django 4.1.1 on 2022-10-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='device name')),
                ('hostname', models.CharField(max_length=255, verbose_name='device fqdn or ip address')),
                ('username', models.CharField(max_length=255, verbose_name='device username')),
                ('password', models.CharField(max_length=255, verbose_name='device password')),
                ('platform', models.CharField(max_length=255, verbose_name='device platform')),
                ('port', models.IntegerField(default=22, verbose_name='ssh port number')),
                ('groups', models.CharField(max_length=255, verbose_name='device groups (comma-separated)')),
                ('data', models.CharField(max_length=255, verbose_name='device data (comma-separated)')),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='group name')),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
    ]
