# Generated by Django 4.1.1 on 2022-10-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='data',
        ),
    ]
