# Generated by Django 4.1.1 on 2022-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_remove_device_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device fqdn or ip address')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device username')),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device password')),
                ('platform', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device platform')),
                ('port', models.IntegerField(blank=True, default=None, null=True, verbose_name='ssh port number')),
                ('groups', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device groups (comma-separated)')),
            ],
            options={
                'db_table': 'defaults',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='groups',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device groups (comma-separated)'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device fqdn or ip address'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device password'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device platform'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='port',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ssh port number'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device username'),
        ),
        migrations.AlterField(
            model_name='device',
            name='groups',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device groups (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device fqdn or ip address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device password'),
        ),
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device platform'),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ssh port number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='device username'),
        ),
    ]
