# Generated by Django 4.1.1 on 2022-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0003_defaults_devicegroup_groups_devicegroup_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults',
            name='data',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='free-form data (json-formatted)'),
        ),
        migrations.AddField(
            model_name='device',
            name='data',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='free-form data (json-formatted)'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='data',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='free-form data (json-formatted)'),
        ),
    ]
