# Generated by Django 4.1.1 on 2022-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0004_defaults_data_device_data_devicegroup_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults',
            name='connection_options',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='free-form data (json-formatted)'),
        ),
        migrations.AddField(
            model_name='device',
            name='connection_options',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='free-form data (json-formatted)'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='connection_options',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='free-form data (json-formatted)'),
        ),
    ]
