# Generated by Django 4.1.1 on 2022-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0005_defaults_connection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaults',
            name='groups',
        ),
        migrations.AlterField(
            model_name='defaults',
            name='connection_options',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='connection options (json-formatted)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='connection_options',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='connection options (json-formatted)'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='connection_options',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='connection options (json-formatted)'),
        ),
    ]
