# Generated by Django 4.1.1 on 2022-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0006_remove_defaults_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEvents',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=255, verbose_name='event name')),
                ('event_message', models.CharField(max_length=255, verbose_name='event message')),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExecutionResults',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hosts', models.CharField(max_length=255, verbose_name='list of hosts for this execution')),
                ('results', models.TextField(verbose_name='result string for execution')),
            ],
            options={
                'db_table': 'results',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='group name'),
        ),
    ]
