# Generated by Django 4.1.1 on 2022-10-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresults',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name of task execution'),
            preserve_default=False,
        ),
    ]
