---
R1:
  hostname: 1.1.1.1
  username: cisco
  password: cisco
  port:     22
  platform: cisco_ios
  groups:
    - 'PE'
  connection_options:
    netmiko:
      extras:
        secret: 'cisco'
  data:
    router_id: 1.1.1.1
    bgp:
      asn: 65000
      peers:
        - ip: 2.2.2.2
          customers:
            - ACME
    customers:
      - name: ACME
        intf: FastEthernet 0/0
        addr: "10.0.1.2 255.255.255.252"
        ospf: 100
        rid:  172.16.10.1
        rd:   "65000:1"
        rt:   "65000:1"
R2:
  hostname: 2.2.2.2
  username: cisco
  password: cisco
  port:     22
  platform: cisco_ios
  groups:
    - 'PE'
  connection_options:
    netmiko:
      extras:
        secret: 'cisco'
  data:
    router_id: 2.2.2.2
    bgp:
      asn: 65000
      peers:
        - ip: 1.1.1.1
          customers:
            - ACME
    customers:
      - name: ACME
        intf: FastEthernet 0/0
        addr: "10.0.2.1 255.255.255.252"
        ospf: 100
        rid:  172.16.20.1
        rd:   "65000:1"
        rt:   "65000:1"
R3:
  hostname: 3.3.3.3
  username: cisco
  password: cisco
  port:     22
  platform: cisco_ios
  groups:
    - 'P'
  connection_options:
    netmiko:
      extras:
        secret: 'cisco'
R4:
  hostname: 4.4.4.4
  username: cisco
  password: cisco
  port:     22
  platform: cisco_ios
  groups:
    - 'P'
  connection_options:
    netmiko:
      extras:
        secret: 'cisco'
R5:
  hostname: 5.5.5.5
  username: cisco
  password: cisco
  port:     22
  platform: cisco_ios
  connection_options:
    netmiko:
      extras:
        secret: 'cisco'
  groups:
    - 'PE'
  data:
    router_id: 5.5.5.5
    bgp:
      asn: 65000
      peers:
    customers:
